### ISSUE TITLE
Guarantees around `ctrl` chan

### ISSUE THREAD

**Issue by wyegelwel** [mpenet/jet#25]
Not an issue as much as a question. What are the guarantees around the `ctrl` chan. 

* Will there be at most 1 item on the channel before close? 
* If there is an ::error pushed onto the channel, does that mean the channel will be closed?

**Comment by mpenet** [comment]
Hi, sorry for the delay, I totally missed this. In http context the :ctrl chan is never closed explicitly. You can have errors such as failure to encode/write to the stream there so no reason to close, the controler can handle retries/failures how they like this way.  

In websocket context it actually is closed after errors at the moment, since it's used for disconnects/network errors only at this point, but I will/might add error handling to socket writing, the same way it's done with http, so dont' have any expectations on that part.
